# Generated by Django 3.1.13 on 2021-11-14 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spirit_topic', '0003_topic_reindex_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicUnread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spirit_topic.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_topics_unread', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'topic unread',
                'verbose_name_plural': 'topics unread',
                'ordering': ['-date', '-pk'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
